System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "build.js": [
      "src/init.js",
      "src/app.js",
      "src/services/movies.js",
      "npm:babel-runtime@5.8.38/core-js/promise.js",
      "npm:core-js@1.2.7/library/fn/promise.js",
      "npm:core-js@1.2.7/library/modules/$.core.js",
      "npm:core-js@1.2.7/library/modules/es6.promise.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.9.js",
      "npm:process@0.11.9/browser.js",
      "npm:core-js@1.2.7/library/modules/$.iter-detect.js",
      "npm:core-js@1.2.7/library/modules/$.wks.js",
      "npm:core-js@1.2.7/library/modules/$.global.js",
      "npm:core-js@1.2.7/library/modules/$.uid.js",
      "npm:core-js@1.2.7/library/modules/$.shared.js",
      "npm:core-js@1.2.7/library/modules/$.set-species.js",
      "npm:core-js@1.2.7/library/modules/$.descriptors.js",
      "npm:core-js@1.2.7/library/modules/$.fails.js",
      "npm:core-js@1.2.7/library/modules/$.js",
      "npm:core-js@1.2.7/library/modules/$.set-to-string-tag.js",
      "npm:core-js@1.2.7/library/modules/$.has.js",
      "npm:core-js@1.2.7/library/modules/$.redefine-all.js",
      "npm:core-js@1.2.7/library/modules/$.redefine.js",
      "npm:core-js@1.2.7/library/modules/$.hide.js",
      "npm:core-js@1.2.7/library/modules/$.property-desc.js",
      "npm:core-js@1.2.7/library/modules/$.microtask.js",
      "npm:core-js@1.2.7/library/modules/$.cof.js",
      "npm:core-js@1.2.7/library/modules/$.task.js",
      "npm:core-js@1.2.7/library/modules/$.dom-create.js",
      "npm:core-js@1.2.7/library/modules/$.is-object.js",
      "npm:core-js@1.2.7/library/modules/$.html.js",
      "npm:core-js@1.2.7/library/modules/$.invoke.js",
      "npm:core-js@1.2.7/library/modules/$.ctx.js",
      "npm:core-js@1.2.7/library/modules/$.a-function.js",
      "npm:core-js@1.2.7/library/modules/$.species-constructor.js",
      "npm:core-js@1.2.7/library/modules/$.an-object.js",
      "npm:core-js@1.2.7/library/modules/$.same-value.js",
      "npm:core-js@1.2.7/library/modules/$.set-proto.js",
      "npm:core-js@1.2.7/library/modules/$.for-of.js",
      "npm:core-js@1.2.7/library/modules/core.get-iterator-method.js",
      "npm:core-js@1.2.7/library/modules/$.iterators.js",
      "npm:core-js@1.2.7/library/modules/$.classof.js",
      "npm:core-js@1.2.7/library/modules/$.to-length.js",
      "npm:core-js@1.2.7/library/modules/$.to-integer.js",
      "npm:core-js@1.2.7/library/modules/$.is-array-iter.js",
      "npm:core-js@1.2.7/library/modules/$.iter-call.js",
      "npm:core-js@1.2.7/library/modules/$.strict-new.js",
      "npm:core-js@1.2.7/library/modules/$.export.js",
      "npm:core-js@1.2.7/library/modules/$.library.js",
      "npm:core-js@1.2.7/library/modules/web.dom.iterable.js",
      "npm:core-js@1.2.7/library/modules/es6.array.iterator.js",
      "npm:core-js@1.2.7/library/modules/$.iter-define.js",
      "npm:core-js@1.2.7/library/modules/$.iter-create.js",
      "npm:core-js@1.2.7/library/modules/$.to-iobject.js",
      "npm:core-js@1.2.7/library/modules/$.defined.js",
      "npm:core-js@1.2.7/library/modules/$.iobject.js",
      "npm:core-js@1.2.7/library/modules/$.iter-step.js",
      "npm:core-js@1.2.7/library/modules/$.add-to-unscopables.js",
      "npm:core-js@1.2.7/library/modules/es6.string.iterator.js",
      "npm:core-js@1.2.7/library/modules/$.string-at.js",
      "npm:core-js@1.2.7/library/modules/es6.object.to-string.js",
      "npm:babel-runtime@5.8.38/core-js/reflect/apply.js",
      "npm:core-js@1.2.7/library/fn/reflect/apply.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.apply.js",
      "npm:babel-runtime@5.8.38/helpers/inherits.js",
      "npm:babel-runtime@5.8.38/core-js/object/set-prototype-of.js",
      "npm:core-js@1.2.7/library/fn/object/set-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/es6.object.set-prototype-of.js",
      "npm:babel-runtime@5.8.38/core-js/object/create.js",
      "npm:core-js@1.2.7/library/fn/object/create.js",
      "npm:babel-runtime@5.8.38/helpers/get.js",
      "npm:babel-runtime@5.8.38/core-js/object/get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/fn/object/get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/modules/es6.object.get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/modules/$.object-sap.js",
      "npm:babel-runtime@5.8.38/helpers/class-call-check.js",
      "npm:babel-runtime@5.8.38/helpers/create-class.js",
      "npm:babel-runtime@5.8.38/core-js/object/define-property.js",
      "npm:core-js@1.2.7/library/fn/object/define-property.js",
      "src/views/list/list.js",
      "src/views/list/card.js",
      "npm:jquery@2.2.4.js",
      "npm:jquery@2.2.4/dist/jquery.js",
      "src/views/list/templates/card.hbs!github:davis/plugin-hbs@1.2.3.js",
      "github:components/handlebars.js@4.0.5/handlebars.runtime.js",
      "src/views/list/templates/list.hbs!github:davis/plugin-hbs@1.2.3.js",
      "src/views/layout/layout.js",
      "src/views/layout/templates/layout.hbs!github:davis/plugin-hbs@1.2.3.js",
      "src/views/layout/templates/header/search.hbs!github:davis/plugin-hbs@1.2.3.js",
      "src/views/layout/templates/header/popular.hbs!github:davis/plugin-hbs@1.2.3.js",
      "src/views/header/header.js",
      "github:dennyferra/TypeWatch@2.2.2.js",
      "github:dennyferra/TypeWatch@2.2.2/jquery.typewatch.js",
      "src/views/header/templates/header.hbs!github:davis/plugin-hbs@1.2.3.js",
      "npm:weakee@1.0.0.js",
      "npm:weakee@1.0.0/weakee.js",
      "npm:babel-runtime@5.8.38/core-js/weak-map.js",
      "npm:core-js@1.2.7/library/fn/weak-map.js",
      "npm:core-js@1.2.7/library/modules/es6.weak-map.js",
      "npm:core-js@1.2.7/library/modules/$.collection.js",
      "npm:core-js@1.2.7/library/modules/$.collection-weak.js",
      "npm:core-js@1.2.7/library/modules/$.array-methods.js",
      "npm:core-js@1.2.7/library/modules/$.array-species-create.js",
      "npm:core-js@1.2.7/library/modules/$.is-array.js",
      "npm:core-js@1.2.7/library/modules/$.to-object.js",
      "github:Semantic-Org/Semantic-UI@2.2.7/semantic.js",
      "github:Semantic-Org/Semantic-UI@2.2.7/semantic.css!github:systemjs/plugin-css@0.1.32.js",
      "npm:jquery.easing@1.4.1.js",
      "npm:jquery.easing@1.4.1/jquery.easing.js",
      "npm:babel-core@5.8.38/polyfill.js",
      "npm:babel-core@5.8.38/lib/polyfill.js",
      "npm:babel-runtime@5.8.38/regenerator/runtime.js",
      "npm:babel-runtime@5.8.38/core-js/symbol.js",
      "npm:core-js@1.2.7/library/fn/symbol.js",
      "npm:core-js@1.2.7/library/fn/symbol/index.js",
      "npm:core-js@1.2.7/library/modules/es6.symbol.js",
      "npm:core-js@1.2.7/library/modules/$.enum-keys.js",
      "npm:core-js@1.2.7/library/modules/$.get-names.js",
      "npm:core-js@1.2.7/library/modules/$.keyof.js",
      "npm:core-js@1.2.7/shim.js",
      "npm:core-js@1.2.7/modules/$.core.js",
      "npm:core-js@1.2.7/modules/web.dom.iterable.js",
      "npm:core-js@1.2.7/modules/$.wks.js",
      "npm:core-js@1.2.7/modules/$.global.js",
      "npm:core-js@1.2.7/modules/$.uid.js",
      "npm:core-js@1.2.7/modules/$.shared.js",
      "npm:core-js@1.2.7/modules/$.iterators.js",
      "npm:core-js@1.2.7/modules/$.hide.js",
      "npm:core-js@1.2.7/modules/$.descriptors.js",
      "npm:core-js@1.2.7/modules/$.fails.js",
      "npm:core-js@1.2.7/modules/$.property-desc.js",
      "npm:core-js@1.2.7/modules/$.js",
      "npm:core-js@1.2.7/modules/es6.array.iterator.js",
      "npm:core-js@1.2.7/modules/$.iter-define.js",
      "npm:core-js@1.2.7/modules/$.set-to-string-tag.js",
      "npm:core-js@1.2.7/modules/$.has.js",
      "npm:core-js@1.2.7/modules/$.iter-create.js",
      "npm:core-js@1.2.7/modules/$.redefine.js",
      "npm:core-js@1.2.7/modules/$.export.js",
      "npm:core-js@1.2.7/modules/$.ctx.js",
      "npm:core-js@1.2.7/modules/$.a-function.js",
      "npm:core-js@1.2.7/modules/$.library.js",
      "npm:core-js@1.2.7/modules/$.to-iobject.js",
      "npm:core-js@1.2.7/modules/$.defined.js",
      "npm:core-js@1.2.7/modules/$.iobject.js",
      "npm:core-js@1.2.7/modules/$.cof.js",
      "npm:core-js@1.2.7/modules/$.iter-step.js",
      "npm:core-js@1.2.7/modules/$.add-to-unscopables.js",
      "npm:core-js@1.2.7/modules/web.immediate.js",
      "npm:core-js@1.2.7/modules/$.task.js",
      "npm:core-js@1.2.7/modules/$.dom-create.js",
      "npm:core-js@1.2.7/modules/$.is-object.js",
      "npm:core-js@1.2.7/modules/$.html.js",
      "npm:core-js@1.2.7/modules/$.invoke.js",
      "npm:core-js@1.2.7/modules/web.timers.js",
      "npm:core-js@1.2.7/modules/$.partial.js",
      "npm:core-js@1.2.7/modules/$.path.js",
      "npm:core-js@1.2.7/modules/js.array.statics.js",
      "npm:core-js@1.2.7/modules/es7.set.to-json.js",
      "npm:core-js@1.2.7/modules/$.collection-to-json.js",
      "npm:core-js@1.2.7/modules/$.classof.js",
      "npm:core-js@1.2.7/modules/$.for-of.js",
      "npm:core-js@1.2.7/modules/core.get-iterator-method.js",
      "npm:core-js@1.2.7/modules/$.to-length.js",
      "npm:core-js@1.2.7/modules/$.to-integer.js",
      "npm:core-js@1.2.7/modules/$.an-object.js",
      "npm:core-js@1.2.7/modules/$.is-array-iter.js",
      "npm:core-js@1.2.7/modules/$.iter-call.js",
      "npm:core-js@1.2.7/modules/es7.map.to-json.js",
      "npm:core-js@1.2.7/modules/es7.object.entries.js",
      "npm:core-js@1.2.7/modules/$.object-to-array.js",
      "npm:core-js@1.2.7/modules/es7.object.values.js",
      "npm:core-js@1.2.7/modules/es7.object.get-own-property-descriptors.js",
      "npm:core-js@1.2.7/modules/$.own-keys.js",
      "npm:core-js@1.2.7/modules/es7.regexp.escape.js",
      "npm:core-js@1.2.7/modules/$.replacer.js",
      "npm:core-js@1.2.7/modules/es7.string.trim-right.js",
      "npm:core-js@1.2.7/modules/$.string-trim.js",
      "npm:core-js@1.2.7/modules/es7.string.trim-left.js",
      "npm:core-js@1.2.7/modules/es7.string.pad-right.js",
      "npm:core-js@1.2.7/modules/$.string-pad.js",
      "npm:core-js@1.2.7/modules/$.string-repeat.js",
      "npm:core-js@1.2.7/modules/es7.string.pad-left.js",
      "npm:core-js@1.2.7/modules/es7.string.at.js",
      "npm:core-js@1.2.7/modules/$.string-at.js",
      "npm:core-js@1.2.7/modules/es7.array.includes.js",
      "npm:core-js@1.2.7/modules/$.array-includes.js",
      "npm:core-js@1.2.7/modules/$.to-index.js",
      "npm:core-js@1.2.7/modules/es6.reflect.set-prototype-of.js",
      "npm:core-js@1.2.7/modules/$.set-proto.js",
      "npm:core-js@1.2.7/modules/es6.reflect.set.js",
      "npm:core-js@1.2.7/modules/es6.reflect.prevent-extensions.js",
      "npm:core-js@1.2.7/modules/es6.reflect.own-keys.js",
      "npm:core-js@1.2.7/modules/es6.reflect.is-extensible.js",
      "npm:core-js@1.2.7/modules/es6.reflect.has.js",
      "npm:core-js@1.2.7/modules/es6.reflect.get-prototype-of.js",
      "npm:core-js@1.2.7/modules/es6.reflect.get-own-property-descriptor.js",
      "npm:core-js@1.2.7/modules/es6.reflect.get.js",
      "npm:core-js@1.2.7/modules/es6.reflect.enumerate.js",
      "npm:core-js@1.2.7/modules/es6.reflect.delete-property.js",
      "npm:core-js@1.2.7/modules/es6.reflect.define-property.js",
      "npm:core-js@1.2.7/modules/es6.reflect.construct.js",
      "npm:core-js@1.2.7/modules/es6.reflect.apply.js",
      "npm:core-js@1.2.7/modules/es6.weak-set.js",
      "npm:core-js@1.2.7/modules/$.collection.js",
      "npm:core-js@1.2.7/modules/$.iter-detect.js",
      "npm:core-js@1.2.7/modules/$.strict-new.js",
      "npm:core-js@1.2.7/modules/$.redefine-all.js",
      "npm:core-js@1.2.7/modules/$.collection-weak.js",
      "npm:core-js@1.2.7/modules/$.array-methods.js",
      "npm:core-js@1.2.7/modules/$.array-species-create.js",
      "npm:core-js@1.2.7/modules/$.is-array.js",
      "npm:core-js@1.2.7/modules/$.to-object.js",
      "npm:core-js@1.2.7/modules/es6.weak-map.js",
      "npm:core-js@1.2.7/modules/es6.set.js",
      "npm:core-js@1.2.7/modules/$.collection-strong.js",
      "npm:core-js@1.2.7/modules/$.set-species.js",
      "npm:core-js@1.2.7/modules/es6.map.js",
      "npm:core-js@1.2.7/modules/es6.promise.js",
      "npm:core-js@1.2.7/modules/$.microtask.js",
      "npm:core-js@1.2.7/modules/$.species-constructor.js",
      "npm:core-js@1.2.7/modules/$.same-value.js",
      "npm:core-js@1.2.7/modules/es6.regexp.split.js",
      "npm:core-js@1.2.7/modules/$.fix-re-wks.js",
      "npm:core-js@1.2.7/modules/es6.regexp.search.js",
      "npm:core-js@1.2.7/modules/es6.regexp.replace.js",
      "npm:core-js@1.2.7/modules/es6.regexp.match.js",
      "npm:core-js@1.2.7/modules/es6.regexp.flags.js",
      "npm:core-js@1.2.7/modules/$.flags.js",
      "npm:core-js@1.2.7/modules/es6.regexp.constructor.js",
      "npm:core-js@1.2.7/modules/$.is-regexp.js",
      "npm:core-js@1.2.7/modules/es6.array.find-index.js",
      "npm:core-js@1.2.7/modules/es6.array.find.js",
      "npm:core-js@1.2.7/modules/es6.array.fill.js",
      "npm:core-js@1.2.7/modules/$.array-fill.js",
      "npm:core-js@1.2.7/modules/es6.array.copy-within.js",
      "npm:core-js@1.2.7/modules/$.array-copy-within.js",
      "npm:core-js@1.2.7/modules/es6.array.species.js",
      "npm:core-js@1.2.7/modules/es6.array.of.js",
      "npm:core-js@1.2.7/modules/es6.array.from.js",
      "npm:core-js@1.2.7/modules/es6.string.starts-with.js",
      "npm:core-js@1.2.7/modules/$.fails-is-regexp.js",
      "npm:core-js@1.2.7/modules/$.string-context.js",
      "npm:core-js@1.2.7/modules/es6.string.repeat.js",
      "npm:core-js@1.2.7/modules/es6.string.includes.js",
      "npm:core-js@1.2.7/modules/es6.string.ends-with.js",
      "npm:core-js@1.2.7/modules/es6.string.code-point-at.js",
      "npm:core-js@1.2.7/modules/es6.string.iterator.js",
      "npm:core-js@1.2.7/modules/es6.string.trim.js",
      "npm:core-js@1.2.7/modules/es6.string.raw.js",
      "npm:core-js@1.2.7/modules/es6.string.from-code-point.js",
      "npm:core-js@1.2.7/modules/es6.math.trunc.js",
      "npm:core-js@1.2.7/modules/es6.math.tanh.js",
      "npm:core-js@1.2.7/modules/$.math-expm1.js",
      "npm:core-js@1.2.7/modules/es6.math.sinh.js",
      "npm:core-js@1.2.7/modules/es6.math.sign.js",
      "npm:core-js@1.2.7/modules/$.math-sign.js",
      "npm:core-js@1.2.7/modules/es6.math.log2.js",
      "npm:core-js@1.2.7/modules/es6.math.log1p.js",
      "npm:core-js@1.2.7/modules/$.math-log1p.js",
      "npm:core-js@1.2.7/modules/es6.math.log10.js",
      "npm:core-js@1.2.7/modules/es6.math.imul.js",
      "npm:core-js@1.2.7/modules/es6.math.hypot.js",
      "npm:core-js@1.2.7/modules/es6.math.fround.js",
      "npm:core-js@1.2.7/modules/es6.math.expm1.js",
      "npm:core-js@1.2.7/modules/es6.math.cosh.js",
      "npm:core-js@1.2.7/modules/es6.math.clz32.js",
      "npm:core-js@1.2.7/modules/es6.math.cbrt.js",
      "npm:core-js@1.2.7/modules/es6.math.atanh.js",
      "npm:core-js@1.2.7/modules/es6.math.asinh.js",
      "npm:core-js@1.2.7/modules/es6.math.acosh.js",
      "npm:core-js@1.2.7/modules/es6.number.parse-int.js",
      "npm:core-js@1.2.7/modules/es6.number.parse-float.js",
      "npm:core-js@1.2.7/modules/es6.number.min-safe-integer.js",
      "npm:core-js@1.2.7/modules/es6.number.max-safe-integer.js",
      "npm:core-js@1.2.7/modules/es6.number.is-safe-integer.js",
      "npm:core-js@1.2.7/modules/$.is-integer.js",
      "npm:core-js@1.2.7/modules/es6.number.is-nan.js",
      "npm:core-js@1.2.7/modules/es6.number.is-integer.js",
      "npm:core-js@1.2.7/modules/es6.number.is-finite.js",
      "npm:core-js@1.2.7/modules/es6.number.epsilon.js",
      "npm:core-js@1.2.7/modules/es6.number.constructor.js",
      "npm:core-js@1.2.7/modules/$.to-primitive.js",
      "npm:core-js@1.2.7/modules/es6.function.has-instance.js",
      "npm:core-js@1.2.7/modules/es6.function.name.js",
      "npm:core-js@1.2.7/modules/es6.object.get-own-property-names.js",
      "npm:core-js@1.2.7/modules/$.get-names.js",
      "npm:core-js@1.2.7/modules/$.object-sap.js",
      "npm:core-js@1.2.7/modules/es6.object.keys.js",
      "npm:core-js@1.2.7/modules/es6.object.get-prototype-of.js",
      "npm:core-js@1.2.7/modules/es6.object.get-own-property-descriptor.js",
      "npm:core-js@1.2.7/modules/es6.object.is-extensible.js",
      "npm:core-js@1.2.7/modules/es6.object.is-sealed.js",
      "npm:core-js@1.2.7/modules/es6.object.is-frozen.js",
      "npm:core-js@1.2.7/modules/es6.object.prevent-extensions.js",
      "npm:core-js@1.2.7/modules/es6.object.seal.js",
      "npm:core-js@1.2.7/modules/es6.object.freeze.js",
      "npm:core-js@1.2.7/modules/es6.object.to-string.js",
      "npm:core-js@1.2.7/modules/es6.object.set-prototype-of.js",
      "npm:core-js@1.2.7/modules/es6.object.is.js",
      "npm:core-js@1.2.7/modules/es6.object.assign.js",
      "npm:core-js@1.2.7/modules/$.object-assign.js",
      "npm:core-js@1.2.7/modules/es6.symbol.js",
      "npm:core-js@1.2.7/modules/$.enum-keys.js",
      "npm:core-js@1.2.7/modules/$.keyof.js",
      "npm:core-js@1.2.7/modules/es5.js"
    ]
  },

  map: {
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "core-js": "npm:core-js@1.2.7",
    "css": "github:systemjs/plugin-css@0.1.32",
    "dennyferra/TypeWatch": "github:dennyferra/TypeWatch@2.2.2",
    "hbs": "github:davis/plugin-hbs@1.2.3",
    "jquery": "npm:jquery@2.2.4",
    "jquery.easing": "npm:jquery.easing@1.4.1",
    "semantic-ui": "github:Semantic-Org/Semantic-UI@2.2.7",
    "weakee": "npm:weakee@1.0.0",
    "github:Semantic-Org/Semantic-UI@2.2.7": {
      "css": "github:systemjs/plugin-css@0.1.32",
      "jquery": "npm:jquery@2.2.4"
    },
    "github:davis/plugin-hbs@1.2.3": {
      "handlebars": "github:components/handlebars.js@4.0.5"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.9"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.8",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-js@1.2.7": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:fs-extra@2.0.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "graceful-fs": "npm:graceful-fs@4.1.11",
      "jsonfile": "npm:jsonfile@2.4.0",
      "os": "github:jspm/nodelibs-os@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:graceful-fs@4.1.11": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:jquery.easing@1.4.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:jsonfile@2.4.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "graceful-fs": "npm:graceful-fs@4.1.11"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.9": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    }
  }
});
